# Generated by Django 4.2.1 on 2023-05-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_picture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
