# Generated by Django 4.2.1 on 2023-05-31 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_picture_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 14, 41, 56, 428016)),
        ),
    ]
