# Generated by Django 4.2.1 on 2023-05-31 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_picture_picture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 14, 54, 10, 116386)),
        ),
    ]
