# Generated by Django 4.2.1 on 2023-06-06 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galery', '0005_alter_picture_picture_alter_picture_picture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 10, 13, 20, 606263)),
        ),
    ]
