# Generated by Django 4.2.1 on 2023-06-06 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_picture_user_alter_picture_picture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 14, 9, 33, 484218)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
